import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { Intro } from "../components/Intro";
import { Words } from "../components/Words";
import { Dedicated } from "../components/Dedicated";
import { Unique } from "../components/Unique";
import { Cases } from "../components/ Cases";
import { Header } from "../components/Header";
import "react-slideshow-image/dist/styles.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vorkweb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box bg="black" color="white">
          <Header />
          <Intro />
          <Words />
          <Dedicated />
          <Unique />
          <Cases />
        </Box>
      </main>
    </>
  );
}
